### ISSUE TITLE
base coding image or gif?

### ISSUE THREAD

**Issue by abtx** [p-j/meteor-crypto-base64#1]
More a question than an issue, really. Does this method work with images and gifs (animated)? Thanks.

**Comment by p-j** [comment]
I'm not sure I understand what you mean.
If what you want is to encode an image in a base64 string in order to include it directly in your HTML or CSS then you can't do it solely using this package.

You would need to read the content of the file first. You can have a look a this [Stack Overflow Answer](http://stackoverflow.com/questions/13034212/converting-the-image-in-base64-string-in-javascript) for hints on how to do it both on the client side and the server side.

Hope this helps.

**Comment by abtx** [comment]
Hi p-j, what I'm trying to do is encode base64 from a remote url, and then pass it to Twitter API (which requires either binary or base64). So basically I want to be able to grab a url from somewhere and pass it over in one of the mentioned encodings. Thanks for your response!

**Comment by p-j** [comment]
What you need is to actually get the content of the file at the given url, and encode this content in base64. Since it's not an issue with the package I'm going to close this.

**Comment by abtx** [comment]
Sure, thanks for the help!
